import { HeartIcon } from '@heroicons/react/outline'
import image from '/public/images/album-image.jpg'

export const playListData = [
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
  {
    image: image,
    song: 'Fake Plastic Trees',
    artist: 'Radiohead',
    album: 'The Bends',
    dateAdded: 'Feb 28, 2019',
    favorite: true,
    duration: '4:14',
  },
]
